### ISSUE TITLE
Basic Level Design

### ISSUE THREAD

**Issue by mr-feek** [feeekkk/ist446-group-game#3]
Create a basic level. This is totally up to how you see the game in your head. Try to keep it symmetrical and maybe two bases on either side? Using the terrain feature would be cool so it's not entirely flat.

**Comment by jcrafts318** [comment]
Parallel to this, let's look for some assets. There's 2 options for how we fit this into our story:

1) this is in 2066, as written in the story. That means future, possibly post-apocalyptic wasteland, since this war is supposed to have been on for 50 years.
2) this whole thing is imagined on the part of the players, and they're actually patients in a mental hospital. This works with our asset design, so it's just as valid as the first option.

I think we ought to do whichever one we can find environment assets for most easily. Let's use tf3dm.com for that.
